/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/components/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        fontSize: {
            xs: "var(--fs-xs)",
            sm: "var(--fs-sm)",
            base: "var(--fs-body)",
        },
        extend: {
            spacing: {
                1: "var(--sp-1)",
                2: "var(--sp-2)",
                3: "var(--sp-3)",
                4: "var(--sp-4)",
                5: "var(--sp-5)",
                6: "var(--sp-6)",
                7: "var(--sp-7)",
                8: "var(--sp-8)",
                9: "var(--sp-9)",
                10: "var(--sp-10)",
                11: "var(--sp-11)",
                12: "var(--sp-12)",
                13: "var(--sp-13)",
                14: "var(--sp-14)",
                15: "var(--sp-15)",
                16: "var(--sp-16)",
            },
            colors: {
                "primary-900": "var(--color-primary-900)",
                "primary-800": "var(--color-primary-800)",
                "primary-700": "var(--color-primary-700)",
                "primary-600": "var(--color-primary-600)",
                "primary-500": "var(--color-primary-500)",
                "primary-400": "var(--color-primary-400)",
                "primary-300": "var(--color-primary-300)",
                "primary-200": "var(--color-primary-200)",
                "primary-100": "var(--color-primary-100)",
                "primary-50": "var(--color-primary-50)",
                "success-900": "var(--color-success-900)",
                "success-800": "var(--color-success-800)",
                "success-700": "var(--color-success-700)",
                "success-600": "var(--color-success-600)",
                "success-500": "var(--color-success-500)",
                "success-400": "var(--color-success-400)",
                "success-300": "var(--color-success-300)",
                "success-200": "var(--color-success-200)",
                "success-100": "var(--color-success-100)",
                "success-50": "var(--color-success-50)",
                "info-900": "var(--color-info-900)",
                "info-800": "var(--color-info-800)",
                "info-700": "var(--color-info-700)",
                "info-600": "var(--color-info-600)",
                "info-500": "var(--color-info-500)",
                "info-400": "var(--color-info-400)",
                "info-300": "var(--color-info-300)",
                "info-200": "var(--color-info-200)",
                "info-100": "var(--color-info-100)",
                "info-50": "var(--color-info-50)",
                "danger-900": "var(--color-danger-900)",
                "danger-800": "var(--color-danger-800)",
                "danger-700": "var(--color-danger-700)",
                "danger-600": "var(--color-danger-600)",
                "danger-500": "var(--color-danger-500)",
                "danger-400": "var(--color-danger-400)",
                "danger-300": "var(--color-danger-300)",
                "danger-200": "var(--color-danger-200)",
                "danger-100": "var(--color-danger-100)",
                "danger-50": "var(--color-danger-50)",
                "warning-900": "var(--color-warning-900)",
                "warning-800": "var(--color-warning-800)",
                "warning-700": "var(--color-warning-700)",
                "warning-600": "var(--color-warning-600)",
                "warning-500": "var(--color-warning-500)",
                "warning-400": "var(--color-warning-400)",
                "warning-300": "var(--color-warning-300)",
                "warning-200": "var(--color-warning-200)",
                "warning-100": "var(--color-warning-100)",
                "warning-50": "var(--color-warning-50)",
                "neutral-900": "var(--color-neutral-900)",
                "neutral-800": "var(--color-neutral-800)",
                "neutral-700": "var(--color-neutral-700)",
                "neutral-600": "var(--color-neutral-600)",
                "neutral-500": "var(--color-neutral-500)",
                "neutral-400": "var(--color-neutral-400)",
                "neutral-300": "var(--color-neutral-300)",
                "neutral-200": "var(--color-neutral-200)",
                "neutral-100": "var(--color-neutral-100)",
                "neutral-50": "var(--color-neutral-50)",
            },
            fontSize: {
                100: "var(--fs-100)",
                200: "var(--fs-200)",
                300: "var(--fs-300)",
                400: "var(--fs-400)",
                500: "var(--fs-500)",
                600: "var(--fs-600)",
                700: "var(--fs-700)",
                800: "var(--fs-800)",
            },
            fontFamily: {
                primary: ["var(--ff-primary)"],
            },
        },
    },
    plugins: [require("@tailwindcss/forms")],
};
